dist: trusty
sudo: false
language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - if [[ $TRAVIS_RUST_VERSION == "nightly" ]]; then cargo install -f clippy && cargo clippy; fi
  - export RUSTFLAGS=-Dwarnings
  - cargo build
  - cargo test --all
