language: rust
sudo: false
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="--deny=warnings"
cache: cargo
rust:

matrix:
  include:
    - rust: stable
      install:
        - rustup component add rustfmt-preview
        - rustup component add clippy-preview
      before_script:
        - cargo fmt --all -- --check
        - cargo clippy --all -- -D clippy::all
    - rust: nightly

script:
  - cargo test --all -- --nocapture
  # Validate benches still work.
  - cargo bench --all -- --test
